 /******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

'use strict';

var fs = require('fs');
var express = require('express');
var app = express();

let months = ['january', 'february', 'march', 'april', 'may', 'june', 'july', 'august', 'september', 'october', 'november', 'december']

if (!process.env.DISABLE_XORIGIN) {
  app.use(function(req, res, next) {
    var allowedOrigins = ['https://narrow-plane.gomix.me', 'https://www.freecodecamp.com'];
    var origin = req.headers.origin || '*';
    if(!process.env.XORIG_RESTRICT || allowedOrigins.indexOf(origin) > -1){
         console.log(origin);
         res.setHeader('Access-Control-Allow-Origin', origin);
         res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    }
    next();
  });
}

app.use('/public', express.static(process.cwd() + '/public'));

app.route('/_api/package.json')
  .get(function(req, res, next) {
    console.log('requested');
    fs.readFile(__dirname + '/package.json', function(err, data) {
      if(err) return next(err);
      res.type('txt').send(data.toString());
    });
  });
  
app.route('/')
    .get(function(req, res) {
		  res.sendFile(process.cwd() + '/views/index.html');
    })

app.route('/:date')
    .get(function(req, res) {
       let date = req.params.date.split(/\-/g);
       if((date.length === 3) || (date.lenght === undefined && Number.isInteger(parseInt(date[0])))){
         if(date.length === 3) {
           let setterOfDay = parseInt(date[0]);
           console.log(setterOfDay);
           let new_date = new Date(date[2], months.indexOf(date[1]), setterOfDay); 
           let day = new_date.getDay();
           let month = months[new_date.getMonth()];
           let year = 1900 + new_date.getYear();
           res.json({ "unix": " " + new_date.getTime()/1000, "natural": " " + day + ", " + month + ", " + year});
         }
         
         else{
           let date = new Date(req.params.date*1000);
           let day = date.getDay();
           let month = months[date.getMonth()];
           let year = 1900 + date.getYear();
           res.json({ "unix": " " + req.params.date, "natural": " " + day + ", " + month + ", " + year});
         }
       }
        else {
          res.json({ "unix": null, "natural": null});
        }
		  
    })

// Respond not found to all the wrong routes
app.use(function(req, res, next){
  res.status(404);
  res.type('txt').send('Not found');
});

// Error Middleware
app.use(function(err, req, res, next) {
  if(err) {
    res.status(err.status || 500)
      .type('txt')
      .send(err.message || 'SERVER ERROR');
  }  
})

app.listen(process.env.PORT, function () {
  console.log('Node.js listening ...');
});
